cmake_minimum_required(VERSION 3.21)
project(TRPLoggingTests LANGUAGES CXX)
find_package(spdlog CONFIG REQUIRED)
enable_testing()
add_executable(LoggingTests LoggingTests.cpp)
target_compile_features(LoggingTests PRIVATE cxx_std_20)
target_compile_definitions(LoggingTests PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
target_include_directories(LoggingTests PRIVATE ../../src)
target_link_libraries(LoggingTests PRIVATE spdlog::spdlog)
foreach(value IN ITEMS unset 0 1 invalid)
    add_test(NAME Logging-${value} COMMAND LoggingTests ${value})
endforeach()
